spring:
  application:
    name: ms-customer
  # Configuracion base de datos reactiva
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/db_customer_dev
    username: postgres
    password: admin
  
server:
  port: 8081 
logging:
  level:
    org.springframework.r2dbc: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
